# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170504_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
