# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
